spring:  h2:    console:      enabled: true
      path: /console
  datasource:    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    initialization-mode: always
    data:    - classpath:data.sql
  jpa:
    hibernate:      ddl-auto: create-drop    show-sql: true
    properties:      hibernate:
        format_sql: true